#GEOGRAPHICAL CONTINENT
AMERICAS = ["NORTHERN_AMERICAN", "CENTRAL_AMERICAN","SOUTH_AMERICAN","LATIN_AMERICAN","CARIBBEAN"]
EUROPEAN = ["EUROPEAN", "WESTERN_EUROPEAN", "EASTERN_EUROPEAN", "NORTHERN_EUROPEAN", "SOUTHERN_EUROPEAN"]
ANTARCTICA = ["ANTARCTICA"]
AFRICAN = ["AFRICAN", "NORTH_AFRICAN", "MIDDLE_AFRICAN","EASTERN_AFRICAN","WESTERN_AFRICAN","SOUTH_AFRICAN"]
ASIAN = ["ASIAN", "SOUTHERN_ASIAN", "CENTRAL_ASIAN", "EASTERN_ASIAN", "SOUTH_EASTERN_ASIAN", "WESTERN_ASIAN"]
OCEANIA = ["AUSTRALIA_NEW_ZEALAND", "MELANASIA", "MICRONESIA", "POLYNESIA", "PACIFIC_ISLANDER"]

#MIXED GEOGRAPHICAL REGIONS
WESTERN_OCCIDENTALE = ["WESTERN_OCCIDENTALE"]
EASTERN_ORIENT = ["EASTERN_ORIENT"]
EURASIA = ["EURASIA", "INDO_EUROPEAN"]
MIDDLE_EASTERN=["MIDDLE_EASTERN"]

#ETHNICITIES AS WE MORE COMMONLY KNOW IT
CAUCASIAN = ["CAUCASIAN"]
BLACK = ["BLACK"]
HISPANIC = ["HISPANIC"]
NON_HISPANIC = ["NON_HISPANIC"]
NON_LATINO = ["NON_LATINO"]
ARAB = ["ARAB"]
PARDO = ["PARDO"]
MESTIZO = ["MESTIZO"]
MULATTO = ["MULATTO"]
INDIGENOUS = ["INDIGENOUS"]
COLOURED = ["COLOURED"]
MIXED = ["MIXED"]

#RELIGIOUS GROUPS
RELIGIOUS = ["CHRISTIAN", "ISLAM", "ORTHODOX", "JEWISH", "SEMITIC", "BUDDHISM", "HINDU", "SIKH", "RELIGIOUS", "JAINISM",
             "MENNONITE"]
AGNOSTIC = ["AGNOSTIC"]
ATHEIST = ["ATHEIST"]

#OTHER/MISSING
FRANCOPHONE = ["FRANCOPHONE"]
ANGLOPHONE = ["ANGLOPHONE"]
MISSING = ["MISSING"]
MINORITY=["MINORITY"]
ETHNIC = ["ETHNIC"]

granularity3_dictionary = {'AMERICAS': AMERICAS, 'EUROPEAN': EUROPEAN, 'ANTARCTICA': ANTARCTICA, 'AFRICAN': AFRICAN,
                           'ASIAN': ASIAN, 'OCEANIA': OCEANIA, 'WESTERN_OCCIDENTALE': WESTERN_OCCIDENTALE,
                           'EASTERN_ORIENT': EASTERN_ORIENT, 'EURASIA': EURASIA, 'MIDDLE_EASTERN': MIDDLE_EASTERN,
                           'CAUCASIAN': CAUCASIAN, 'BLACK': BLACK, 'HISPANIC': HISPANIC, 'NON_HISPANIC':NON_HISPANIC,
                           'NON_LATINO': NON_LATINO, 'ARAB': ARAB, 'PARDO': PARDO, 'MESTIZO': MESTIZO,
                           'MULATTO': MULATTO, 'INDIGENOUS': INDIGENOUS, 'COLOURED': COLOURED, 'MIXED': MIXED,
                           'RELIGIOUS': RELIGIOUS, 'AGNOSTIC':AGNOSTIC, 'ATHEIST': ATHEIST, 'FRANCOPHONE': FRANCOPHONE,
                           'ANGLOPHONE': ANGLOPHONE, 'MISSING': MISSING, 'MINORITY': MINORITY, 'ETHNIC': ETHNIC}